# Gradient Descent

Learning in machine learning is about finding the weights $W$ that minimizes the cost or loss function:

$$arg_{w}min \ loss(w)$$

In most cases, we will have to find thousands if not millions of these weights, so ofcoures we need to figure out a numerical way to look for them.

The solution lies in **Gradient Descent**:

<img src="imgs/Gradient_Descent.png" />

* $\alpha$: the learning rate (small value like $.01$)
* $\partial{loss} \over \partial{w}$: The gradient of the loss function.

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [33]:
def forward(x):
    return np.multiply(ws_s[-1],x)

All of the functions are imported from the previous notebook, now we need function that will help us update the weights using this formula:

$$w_n \leftarrow w_{n-1} - {\partial{loss} \over \partial{w}}(w_{n-1})$$

first, let's calculate ${\partial{loss} \over \partial{w}}(w)$, first we present the loss function, and we go from there:

$$J(w)={1 \over m}\sum_{i=0}^{m}(\hat{y_i}-y_i)^{2}$$

**We suppose a linear model** of the form $\hat{y_i}=w \cdot x_i$ (without supposing a model, we can't calculate the derivative) so:

$$\Rightarrow J(w)={1 \over m}\sum_{i=0}^{m}({wx_i}-y_i)^{2}$$

$$\Rightarrow {\partial{J} \over \partial{w}}(w) = {1 \over m}\sum_{i=0}^{m}{\partial{} \over \partial{w}}({wx_i}-y_i)^{2}$$

$$\Rightarrow {\partial{J} \over \partial{w}}(w) = {2 \over m}\sum_{i=0}^{m}x_i(\hat{y_i}-y_i)$$

Now, let's implement the gradient of the loss in numpy:

In [59]:
def loss(x, y):
    '''
    Calculates Loss: MSE.
    Actual Solution: (y_hat - y)*(y_hat - y).
    .. Doesn't support vectors.
    '''
    y_hat = forward(x)
    return sum((np.subtract(y_hat,y))**2)/len(y)

In [60]:
def gradient_loss(x, y):
    '''
    Calculates the Gradient Loss of MSE.
    '''
    y_hat = forward(x)
    return sum(np.multiply(np.subtract(y_hat,y), x))*2/len(y)

In [71]:
# training data.
X = [1, 2, 3, 4, 5]
y = [8, 16, 24, 32, 40]

In [72]:
# weights.
w_s = np.arange(0, 20, 0.1)

In [73]:
losses = []
gradient_losses = []
for w in w_s:
    losses.append(loss(X, y))
    gradient_losses.append(gradient_loss(X, y))

Let's plot the **Weights vs. Loss** then **Loss vs. Gradient Loss**:

In [74]:
plt.plot(w_s, losses)

plt.xlabel('Weight')
plt.ylabel('Loss')

plt.title('Weight vs. Loss')
plt.show()

In [75]:
plt.plot(gradient_losses, losses)

plt.xlabel('Gradient Loss')
plt.ylabel('Loss')

plt.title('Loss vs. Gradient')
plt.show()

Now, instead of random weights, we will update our weight each time, and calculate the gradient loss and do it again, until the loss is small enough:

In [78]:
ws_s = [15]
X    = [1, 2, 3, 4, 5]
y    = [8, 16, 24, 32, 40]

In [79]:
alpha = 0.01
losses = []
preds = []
g_losses = []

while True:
    # first we calculate the preds.
    y_h = forward(X)
    preds.append(y_h)
    
    # we calculate the loss.
    l = loss(X, y)
    losses.append(l)
    
    # we break if we have a sufficiently small loss.
    if l < 1:
        break
    
    # if not, we calculate the gradient loss.
    g_loss = gradient_loss(X, y)
    g_losses.append(g_loss)
    
    # and we update the weight.
    new_w = ws_s[-1] - (alpha*g_loss)
    ws_s.append(new_w)

In [82]:
losses

[539.0,
 327.92760000000015,
 199.51115184000008,
 121.38258477945612,
 73.84916457982105,
 44.929831730363105,
 27.33530962475292,
 16.630802375699666,
 10.11818016537568,
 6.155900812614562,
 3.7452500543946976,
 2.2786101330937285,
 1.3863064049742218,
 0.8434288167863203]

In [83]:
preds

[array([15, 30, 45, 60, 75]),
 array([13.46, 26.92, 40.38, 53.84, 67.3 ]),
 array([12.2588, 24.5176, 36.7764, 49.0352, 61.294 ]),
 array([11.321864, 22.643728, 33.965592, 45.287456, 56.60932 ]),
 array([10.59105392, 21.18210784, 31.77316176, 42.36421568, 52.9552696 ]),
 array([10.02102206, 20.04204412, 30.06306617, 40.08408823, 50.10511029]),
 array([ 9.5763972 , 19.15279441, 28.72919161, 38.30558882, 47.88198602]),
 array([ 9.22958982, 18.45917964, 27.68876946, 36.91835928, 46.1479491 ]),
 array([ 8.95908006, 17.91816012, 26.87724018, 35.83632024, 44.7954003 ]),
 array([ 8.74808245, 17.49616489, 26.24424734, 34.99232979, 43.74041223]),
 array([ 8.58350431, 17.16700862, 25.75051292, 34.33401723, 42.91752154]),
 array([ 8.45513336, 16.91026672, 25.36540008, 33.82053344, 42.2756668 ]),
 array([ 8.35500402, 16.71000804, 25.06501206, 33.42001608, 41.77502011]),
 array([ 8.27690314, 16.55380627, 24.83070941, 33.10761255, 41.38451568])]

In [84]:
ws_s

[15,
 13.46,
 12.2588,
 11.321864000000001,
 10.59105392,
 10.0210220576,
 9.576397204928,
 9.22958981984384,
 8.959080059478195,
 8.748082446392992,
 8.583504308186534,
 8.455133360385496,
 8.355004021100687,
 8.276903136458536]

**The loss kept getting smaller, the predictions converted to the targets, and the weight converged to $8$, this is the magic of the gradient descent when coupled with a good loss function and a good model (hypothesis space).**

In the case of model of 2 parameters, like this one:

$$\hat{y}=x^{2}w_2 + xw_{1} +b$$
$$J(w)=(\hat{y}_w - y)^2$$

We need to calculate the partial derivative of the loss function with respect to the 2 parameters, as follows:

$${\partial{J} \over \partial{w_1}} = 2x|\hat{y}_w - y|$$
$${\partial{J} \over \partial{w_2}} = 2x^2|\hat{y}_w - y|$$

Then we can update each weight separately as we learn.

### Numpy Implementation